export const PRIMARY_COLOR = "#0D3347"

export const VEHICLE_STATUS_TRANSIT = "On The Way"
export const VEHICLE_STATUS_STOPPED = "Transit"
export const VEHICLE_STATUS_INCOMING = "Incoming"
export const VEHICLE_STATUS_BREAK = "On Break"
export const VEHICLE_STATUS_TRANSIT_BG = "#EFB700"
export const VEHICLE_STATUS_STOPPED_BG = "#008450"
export const VEHICLE_STATUS_INCOMING_BG = "#9ACD32"
export const VEHICLE_STATUS_BREAK_BG = "#B81D13"